export function getCurrencySign(currency: string) {
  return currency === "vnd"
    ? "₫"
    : currency === "sgd"
    ? "SGD"
    : currency === "eur"
    ? "€"
    : currency === "inr"
    ? "₹"
    : currency === "usd"
    ? "$"
    : currency === "cny"
    ? "¥"
    : currency === "jpy"
    ? "¥"
    : currency === "cad"
    ? "C$"
    : currency === "idr"
    ? "Rp"
    : currency === "myr"
    ? "RM"
    : "₱";
}
